### ISSUE TITLE
Works on localhost but not on www

### ISSUE THREAD

**Issue by codingtuba** [codingtuba/accounts.aimedtuba#2]
Error:
  /home/aimehoow/nodevenv/accounts/10/lib/node_modules/whatwg-url/lib/encoding.js:2
  const utf8Encoder = new TextEncoder();
                    ^
  
  ReferenceError: TextEncoder is not defined
      at Object.<anonymous> (/home/aimehoow/nodevenv/accounts/10/lib/node_modules/whatwg-url/lib/encoding.js:2:21)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Module.require (internal/modules/cjs/loader.js:692:17)
      at require (internal/modules/cjs/helpers.js:25:18)  
      at Object.<anonymous> (/home/aimehoow/nodevenv/accounts/10/lib/node_modules/whatwg-url/lib/url-state-machine.js:5:34)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
  /home/aimehoow/nodevenv/accounts/10/lib/node_modules/whatwg-url/lib/encoding.js:2

**Comment by codingtuba-personal** [comment]
Update: error no longer shows, yet application won't start.

**Comment by codingtuba-personal** [comment]
Fixed issue
